marketpulse/main/urls.py
from django.conf import settings
from django.conf.urls import patterns, url, include


urlpatterns = patterns(
    '{0}.main.views'.format(settings.PROJECT_MODULE),
    url(r'^$', 'home', name='home'),
    url(r'^activities/$', 'activities', name='activities'),
    url(r'^manifest\.webapp', 'manifest', name='manifest'),
    url(r'^fxosprice/', include('{0}.main.fxosprice_urls'.format(settings.PROJECT_MODULE))),
    url(r'^media/', include('{0}.main.media_urls'.format(settings.PROJECT_MODULE))),
)

marketpulse/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin


import jingo.monkey


jingo.monkey.patch()

handler404 = 'marketpulse.base.views.custom_404'
handler500 = 'marketpulse.base.views.custom_500'

urlpatterns = patterns(
    '',

    # Apps
    url(r'', include('{0}.auth.urls'.format(settings.PROJECT_MODULE))),
    url(r'', include('{0}.main.urls'.format(settings.PROJECT_MODULE), namespace='main')),

    # Admin
    url(r'^admin/', include(admin.site.urls)),
)

# In DEBUG mode, serve static/media files through Django
if settings.DEBUG:
    urlpatterns += patterns(
        '',
        url(r'^404/$', handler404),
        url(r'^500/$', handler500),
        url(r'^files/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),
    )

marketpulse/devices/models.py
from django.db import models


class Device(models.Model):
    """Model for FfxOS devices data."""

    model = models.CharField(max_length=120, blank=True, default="")
    manufacturer = models.CharField(max_length=120, blank=True, default="")
    is_fxos = models.BooleanField(default=True)

    def __unicode__(self):
        return u'{0}, {1}'.format(self.manufacturer, self.model)

    class Meta:
        ordering = ['manufacturer', 'model']
        unique_together = ('model', 'manufacturer',)

marketpulse/main/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator

from django_countries import countries
from django_countries.fields import CountryField
from uuslug import uuslug
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill

from marketpulse.devices.models import Device
from marketpulse.geo.models import LocationBase
from marketpulse.main import get_currency_choices


class Activity(models.Model):
    """Model for activity types."""

    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=255, blank=True, default='')

    class Meta:
        ordering = ['name']
        verbose_name = 'activity'
        verbose_name_plural = 'activities'

    def __unicode__(self):
        return unicode(self.name)

    def save(self, *args, **kwargs):
        """Custom save method."""

        if not self.id:
            self.slug = uuslug(self.name, instance=self)
        super(Activity, self).save(*args, **kwargs)


class Location(LocationBase):
    """Model for contribution location."""

    address = models.CharField(max_length=120, blank=True, default='')
    shop_name = models.CharField(max_length=120, blank=True, default='Media upload')
    link = models.URLField(max_length=500, blank=True, default='')
    is_online = models.BooleanField(default=False)

    def __unicode__(self):
        return u'{0}, {1}'.format(self.shop_name, self.country)


class Contribution(models.Model):
    """Model for contribution data."""

    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='contributions')
    activity = models.ForeignKey(Activity, related_name='contributions')
    location = models.ForeignKey(Location, related_name='contributions', null=True)
    device = models.ForeignKey(Device, related_name='contributions', null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    comment = models.TextField(blank=True, default='')
    availability = models.BooleanField(default=True)
    image = models.ImageField(upload_to='ffos', blank=True)
    image_thumb = ImageSpecField(source='image',
                                 processors=[ResizeToFill(100, 100)],
                                 format='JPEG',
                                 options={'quality': 60})

    class Meta:
        ordering = ['-updated_on']

    def __unicode__(self):
        return u'{0}, {1}, {2}'.format(self.user, self.activity, self.id)


class Carrier(models.Model):
    name = models.CharField(max_length=128)
    parent_operator = models.CharField(max_length=128, blank=True, default='')
    country = CountryField(null=True, blank=True)

    def __unicode__(self):
        all_countries = dict(countries)
        country = self.country
        if self.country.code in all_countries:
            country = all_countries[self.country.code]

        return u'{0}, {1}, {2}'.format(self.name, country, self.parent_operator)

    class Meta:
        ordering = ['name']


class Plan(models.Model):
    """Mobile phone plan information."""

    contribution = models.ForeignKey(Contribution, related_name='plans', null=True)
    has_plan = models.BooleanField(default=False)
    duration = models.PositiveIntegerField(blank=True, null=True)
    description = models.TextField(default='', blank=True)
    amount = models.FloatField(blank=True, null=True, validators=[MinValueValidator(0.0)])
    currency = models.CharField(max_length=128, choices=get_currency_choices(), default='')
    carrier = models.ForeignKey(Carrier, related_name='carriers', null=True, blank=True)
    monthly_fee = models.FloatField(blank=True, null=True, validators=[MinValueValidator(0.0)])


class Vote(models.Model):
    """Vote model.

    Register the upvotes/confirmations for each contribution.
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='voted_on')
    contribution = models.ForeignKey(Contribution, related_name='votes')
    date_voted = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'contribution',)

    def __unicode__(self):
        return u'{0}, {1}'.format(self.user, self.contribution)

marketpulse/main/views.py
from django.db.models import Count
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.forms.models import inlineformset_factory, model_to_dict
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.core.urlresolvers import reverse
from django.http import Http404
from django.http import HttpResponse

import moneyed
from django_countries import countries

from marketpulse.geo.lookup import reverse_geocode

from marketpulse.main import FFXOS_ACTIVITY_NAME, FFXOS_MEDIA_ACTIVITY_NAME, forms
from marketpulse.main.models import Activity, Contribution, Plan, Vote
from marketpulse.devices.forms import DeviceForm
from marketpulse.devices.models import Device


def home(request):
    """Landing page view."""

    if request.user.is_authenticated():
        return redirect(reverse('main:activities'))
    return render(request, 'home.html')


@login_required
def edit_contribution(request, contribution_pk=None, clone=False):
    """Edit a single contribution."""

    user = request.user

    if request.is_ajax():
        lat = request.GET.get('latitude')
        lng = request.GET.get('longitude')

        data = {'country': None,
                'currency': None}

        location_data = reverse_geocode(lat, lng)
        country_code = location_data.get('country')
        if country_code:
            data['country'] = country_code
            country_name = dict(countries)[country_code]

            for currency, currency_data in moneyed.CURRENCIES.items():
                if country_name.upper() in currency_data.countries:
                    data['currency'] = currency
                    break

        return JsonResponse(data)

    is_fxos = True
    other_device = None
    if not contribution_pk:
        activity = Activity.objects.get(name=FFXOS_ACTIVITY_NAME)
        contribution = Contribution(activity=activity, user=user)
        location = None
        extra = 1
    else:
        if clone:
            contribution = get_object_or_404(Contribution, pk=contribution_pk)
        else:
            contribution = get_object_or_404(Contribution, pk=contribution_pk, user=user)
        location = contribution.location
        extra = 0
        is_fxos = contribution.device.is_fxos
        other_device = model_to_dict(contribution.device) if not is_fxos else None

    location_form = forms.LocationForm(request.POST or None, instance=location)
    PlanFormset = inlineformset_factory(Contribution, Plan, formset=forms.BasePlanFormset,
                                        extra=extra, can_delete=False)
    device_form = DeviceForm(request.POST or None, initial=other_device)
    contribution_form = forms.ContributionForm(request.POST or None, is_fxos=is_fxos,
                                               instance=contribution, clone=clone)
    plan_formset = PlanFormset(request.POST or None, instance=contribution,
                               clone=clone)

    if location_form.is_valid() and plan_formset.is_valid() and device_form.is_valid():
        is_fxos = device_form.cleaned_data['is_fxos']
        contribution_form = forms.ContributionForm(request.POST, instance=contribution,
                                                   is_fxos=is_fxos, clone=clone)
        if contribution_form.is_valid():
            location = location_form.save()
            obj = contribution_form.save(commit=False)
            obj.location = location
            if clone:
                obj.user = user
            if not is_fxos:
                device = device_form.save()
                obj.device = device
            obj.save()
            plan_formset.save()

            messages.success(request, 'Contribution successfully saved')
            contribution_form = forms.ContributionForm()
            location_form = forms.LocationForm()
            plan_formset = PlanFormset()

            return redirect(reverse('main:list_my_contributions'))

    return render(request, 'fxosprice_new.html',
                  {'contribution_form': contribution_form,
                   'device_form': device_form,
                   'location_form': location_form,
                   'plan_formset': plan_formset,
                   'mapbox_id': settings.MAPBOX_MAP_ID,
                   'mapbox_token': settings.MAPBOX_TOKEN})


@login_required
def list_my_contributions(request):
    """View contributions of logged-in user."""

    return list_contributions(request, user=request.user)


@login_required
def list_contributions(request, user=None):
    """View to list either all the contributions
    or the contributions of a user.

    """

    contributions = (Contribution.objects.filter(activity__name=FFXOS_ACTIVITY_NAME)
                     .annotate(total_votes=Count('votes')).order_by('-total_votes'))
    if user:
        contributions = contributions.filter(user=user)

    devices = Device.objects.all()
    all_countries = []
    for code, name in list(countries):
        all_countries.append({'code': code, 'name': name})

    country_code = request.GET.get('country_code')
    device_pk = request.GET.get('device_pk')
    if country_code:
        contributions = contributions.filter(location__country=country_code)
    if device_pk:
        contributions = contributions.filter(device=device_pk)
        device_pk = int(device_pk)

    contributions_paginator = Paginator(contributions, settings.ITEMS_PER_PAGE)
    contributions_page = request.GET.get('page', 1)

    try:
        contributions = contributions_paginator.page(contributions_page)
    except PageNotAnInteger:
        contributions = contributions_paginator.page(1)
    except EmptyPage:
        contributions = contributions_paginator.page(contributions_paginator.num_pages)

    return render(request, 'fxosprice_all.html',
                  {'contributions': contributions,
                   'devices': devices,
                   'countries': all_countries,
                   'country_code': country_code,
                   'device_pk': device_pk})


@login_required
def view_contribution(request, contribution_pk):
    """View a single contribution."""

    user = request.user
    contribution = get_object_or_404(Contribution, pk=contribution_pk)
    user_has_voted = Vote.objects.filter(user=user, contribution=contribution).exists()
    return render(request, 'fxosprice_view.html',
                  {'user': user, 'contribution': contribution,
                   'mapbox_id': settings.MAPBOX_MAP_ID,
                   'mapbox_token': settings.MAPBOX_TOKEN,
                   'user_has_voted': user_has_voted})


@login_required
def verify_contribution(request, contribution_pk):
    """Verify a contribution."""

    user = request.user
    contribution = get_object_or_404(Contribution, pk=contribution_pk)

    if not Vote.objects.filter(user=user, contribution=contribution).exists():
        Vote.objects.create(user=user, contribution=contribution)
    return redirect(reverse('main:list_contributions'))


@login_required
def delete_contribution(request, contribution_pk):
    user = request.user

    if not Contribution.objects.filter(user=user.pk, pk=contribution_pk).exists():
        raise Http404()

    Contribution.objects.get(user=user.pk, pk=contribution_pk).delete()
    messages.success(request, 'Contribution successfully deleted')
    return redirect(reverse('main:list_contributions'))


@login_required
def activities(request):
    user = request.user
    user_contributions = Contribution.objects.filter(user=user.pk).count()
    total_contributions = Contribution.objects.all().count()
    try:
        percent = int((float(user_contributions) / float(total_contributions)) * 100)
    except ZeroDivisionError:
        percent = 0
    return render(request, 'activities.html',
                  {'user': request.user,
                   'user_contributions': user_contributions,
                   'percent': percent})


def manifest(request):
    data = render(request, 'manifest.webapp')
    response = HttpResponse(data,
                            content_type='application/x-web-app-manifest+json; charset=utf-8')
    response['Content-Disposition'] = 'attachment;filename=manifest.webapp'
    return response


@login_required
def new_media(request):
    user = request.user

    activity = Activity.objects.get(name=FFXOS_MEDIA_ACTIVITY_NAME)
    contribution = Contribution(activity=activity, user=user)

    contribution_form = forms.ImageForm(request.POST or None,
                                        request.FILES or None,
                                        instance=contribution)

    location_form = forms.LocationForm(request.POST or None, is_media=True)

    if location_form.is_valid() and contribution_form.is_valid():
        location = location_form.save()
        obj = contribution_form.save(commit=False)
        obj.location = location
        obj.save()

        messages.success(request, 'Contribution successfully saved')
        return redirect(reverse('main:activities'))

    return render(request, 'media_new.html',
                  {'contribution_form': contribution_form,
                   'location_form': location_form,
                   'mapbox_id': settings.MAPBOX_MAP_ID,
                   'mapbox_token': settings.MAPBOX_TOKEN})


def all_media(request):
    """View gallery with all photo contributions"""

    contributions = Contribution.objects.filter(activity__name=FFXOS_MEDIA_ACTIVITY_NAME)

    contributions_paginator = Paginator(contributions, settings.PHOTOS_PER_PAGE)
    contributions_page = request.GET.get('page', 1)

    try:
        contributions = contributions_paginator.page(contributions_page)
    except PageNotAnInteger:
        contributions = contributions_paginator.page(1)
    except EmptyPage:

marketpulse/main/templates/activities.html
{% extends "base.html" %}

{% block content %}
  <div class="row" id="activities-titles">
    <div class="col-md-6">
      <h2>{{ user_contributions }} Contribution{{ user_contributions|pluralize }}</h2>
    </div>
    <div class="col-md-6">
      <h4 class="text-center">
        Your contributions represent<br>
        {{ percent }}% of all contributions
      </h3>
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col-md-12">
      <a href="{{ url('main:new_contribution') }}"
         class="btn btn-lg btn-default btn-block">New Device Price</a>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12 text-right">
      <a href="{{ url('main:list_my_contributions') }}"
         class="view-all">View your contributions</a> &bull;
      <a href="{{ url('main:list_contributions') }}" class="view-all">View all contributions</a>
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col-md-12">
      <a href="{{ url('main:new_media') }}"
         class="btn btn-lg btn-default btn-block">New Photo</a>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12 text-right">
      <a href="{{ url('main:all_media') }}" class="view-all">View gallery</a>
    </div>
  </div>
{% endblock %}

marketpulse/main/templates/fxosprice_all.html
{% extends "base.html" %}

{% block content %}
  <h2 class="title">Device Prices</h2>
  <h3 class="title">Contributions</h3>

  <div class="row">
    <form action="" method="get">
      <div class="col-md-5">
        <div class="form-group">
          <select class="form-control" name="country_code">
            <option value="">All Countries</option>
            {% for country in countries %}
              <option value="{{ country.code }}" {% if country.code == country_code %}selected{% endif %}>
                {{ country.name }}
              </option>
            {% endfor %}
          </select>
        </div>
      </div>
      <div class="col-md-5">
        <div class="form-group">
          <select class="form-control" name="device_pk">
            <option value="">All Devices</option>
            {% for device in devices %}
              <option value="{{ device.pk }}" {% if device.pk == device_pk %}selected{% endif %}>
                {{ device }}
              </option>
            {% endfor %}
          </select>
        </div>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <button type="submit" class="btn btn-default btn-lg">Filter</button>
        </div>
      </div>
    </form>
  </div>

  {% if contributions %}
    <table class="table table-condensed contribution-table">
      <thead>
        <tr>
          <td>Firefox OS</td>
          <td>Device</td>
          <td>When</td>
          <td>Country</td>
          <td class="hidden-xs">Shop</td>
          <td>Contributor</td>
          <td>Verified</td>
          <td></td>
        </tr>
      </thead>
      <tbody>
        {% for contribution in contributions %}
          <tr>
            <td>
              {% if contribution.device.is_fxos %}
                <span class="glyphicon glyphicon-ok"></span>
              {% else %}
                <span class="glyphicon glyphicon-remove"></span>
              {% endif %}
            </td>
            <td>{{ contribution.device }}</td>
            <td>{{ contribution.created_on|date("D d M Y") }}</td>
            <td>{{ contribution.location.country.name }}</td>
            <td class="hidden-xs">{{ contribution.location.shop_name }}</td>
            <td>
              {% if contribution.user == user %}
                That's you!
              {% else %}
                {{ contribution.user.mozillians_username }}
              {% endif %}
            </td>
            <td>
              {% if contribution.votes.exists() %}
                <span class="glyphicon glyphicon-ok"></span>
              {% else %}
                <span class="glyphicon glyphicon-remove"></span>
              {% endif %}
            </td>
            <td class="delete-contribution">
              <a href="{{ url('main:view_contribution', contribution.pk) }}"
                 class="btn btn-default btn-xs">Details</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

    <nav class="text-center">
      <ul class="pagination">
        {% if contributions.has_previous() %}
          <li>
            <a href="{{ '#'|urlparams(page=contributions.previous_page_number()) }}"
               aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
        {% else %}
          <li class="disabled">
            <a href="#" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a>
          </li>
        {% endif %}
        {% for i in range(1, contributions.paginator.num_pages + 1) %}
          <li {% if i == contributions.number %}class="active"{% endif %}>
            <a href="{{ '#'|urlparams(page=i) }}">{{ i }}</a>
          </li>
        {% endfor %}
        {% if contributions.has_next() %}
          <li>
            <a href="{{ '#'|urlparams(page=contributions.next_page_number()) }}"
               aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
        {% else %}
          <li class="disabled">
            <a href="#" aria-label="Previous"><span aria-hidden="true">&raquo;</span></a>
          </li>
        {% endif %}
      </ul>
    </nav>
  {% else %}
    <div class="row">
      <div class="col-md-12 text-center">
        No contributions for this Activity
      </div>
    </div>
  {% endif %}
{% endblock %}

marketpulse/main/templates/fxosprice_new.html
{% extends "base.html" %}

{% block css %}
  <link href="https://api.tiles.mapbox.com/mapbox.js/v2.1.5/mapbox.css" rel="stylesheet" />
  <link href="{{ static('css/map.css') }}" rel="stylesheet" />
{% endblock %}

{% block content %}
  <h2 class="title">New Device Price</h2>

  {% if location_form.errors or contribution_form.errors or plan_formset.errors %}
    <div id="error-div" class="row messages">
      <div class="col-md-12">
        <div class="alert alert-danger" role="alert">
          Please correct the following errors
        </div>
      </div>
    </div>
  {% endif %}

  <form method="post" novalidate>
    {{ csrf() }}

    <div class="row">
      <div class="col-md-6">
        <fieldset>
          <legend>Shop</legend>
          <div class="form-group switch">
            <label for="id_is_online">Is this an online shop?</label>
            <label class="pack-switch">
              {{ location_form.is_online }}
              <span></span>
            </label>
          </div>
          <div class="form-group">
            {{ field_with_attrs(location_form.shop_name,
                                placeholder="Please provide the name of the shop")}}
            {{ field_errors(location_form.shop_name) }}
          </div>
          <div class="form-group" id="onlineshop">
            <div class="form-group">
              {{ field_with_attrs(location_form.link, placeholder="http://www.example.com") }}
              {{ field_errors(location_form.link) }}
            </div>
            <div class="form-group">
              {{ field_with_attrs(location_form.country, class="form-control") }}
            </div>
            {{ field_errors(location_form.country) }}
          </div>
        </fieldset>

        <fieldset id="location">
          <legend>Location</legend>
          <div class="form-group">
            <div id="map" data-mapboxid="{{ mapbox_id }}" data-mapboxtoken="{{ mapbox_token }}"></div>
            <small id="location-text">Getting your location...</small>
            {{ location_form.lat }}
            {{ location_form.lng }}
          </div>
          {{ field_errors(location_form.lat) }}
          {{ field_errors(location_form.lng) }}
        </fieldset>

        <fieldset>
          <legend>Device</legend>
          <div class="switch is-fxos">
            <label for="id_is_fxos">Is this a Firefox OS device?</label>
            <label class="pack-switch">
              {{ device_form.is_fxos }}
              <span></span>
            </label>
          </div>
          <div class="form-group other-device">
            {{ field_with_attrs(device_form.model, placeholder="Device model") }}
            {{ field_errors(device_form.model) }}
            {{ field_with_attrs(device_form.manufacturer, placeholder="Device manufacturer") }}
            {{ field_errors(device_form.manufacturer) }}
          </div>
          <div class="form-group fxos-device">
            {{ field_with_attrs(contribution_form.device, class="form-control") }}
          </div>
          {{ field_errors(contribution_form.device) }}
          <div class="form-group switch">
            <label for="id_availability">In stock</label>
            <label class="pack-switch">
              {{ contribution_form.availability }}
              <span></span>
            </label>
          </div>
        </fieldset>
      </div>
      <div class="col-md-6">
        <fieldset>
          <legend>Device Prices</legend>
          <div id="fieldset-planprices">
            <div class="form-group planprices">
              {% for plan_form in plan_formset %}
                {% for hidden in plan_form.hidden_fields() %}
                  {{ hidden }}
                {% endfor %}
                <div class="plan-form">
                  <div class="form-group switch">
                    <label for="id_{{ plan_form.prefix}}-has_plan">
                      Is this price part of a plan?
                    </label>
                    <label class="pack-switch">
                      {{ field_with_attrs(plan_form.has_plan, class="hasplan-check") }}
                      <span></span>
                    </label>
                    {{ field_errors(plan_form.has_plan) }}
                  </div>
                  <div class="row">
                    <div class="col-xs-8">
                      {{ field_with_attrs(plan_form.amount, placeholder="Device Price", min="0") }}
                      {{ field_errors(plan_form.amount) }}
                    </div>
                    <div class="col-xs-4">
                      {{ field_with_attrs(plan_form.currency, class="form-control formset-currency")}}
                      {{ field_errors(plan_form.currency) }}
                    </div>
                  </div>
                  <div id="hasplan-{{ plan_form.prefix }}" class="form-group hasplan">
                    {{ field_with_attrs(plan_form.carrier,
                                        placeholder="Carrier name",
                                        class="form-control") }}
                    {{ field_errors(plan_form.carrier) }}
                  </div>
                  <div class="form-group hasplan">
                    <label></label>
                    {{ field_with_attrs(plan_form.monthly_fee, placeholder="Monthly fee") }}
                    {{ field_errors(plan_form.monthly_fee) }}
                  </div>
                  <div class="form-group hasplan">
                    {{ field_with_attrs(plan_form.description,
                                        placeholder="Plan description (eg. title)") }}
                    {{ field_errors(plan_form.description) }}
                  </div>
                  <div class="form-group hasplan">
                    <label></label>
                    {{ field_with_attrs(plan_form.duration,
                                        placeholder="Plan duration (in months)") }}
                    {{ field_errors(plan_form.duration) }}
                  </div>
                </div>
              {% endfor %}
            </div>
          </div>
          {{ plan_formset.management_form }}
        </fieldset>
        <fieldset>
          <legend>Comment</legend>
          <div class="form-group">
            {{ field_with_attrs(contribution_form.comment,
                                rows="3",
                                placeholder="Add any comments")}}
          </div>
        </fieldset>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 text-right">
        <button type="submit" class="btn btn-lg btn-primary">Submit</button>
      </div>
    </div>
  </form>
{% endblock %}

{% block js %}
  <script src="https://api.tiles.mapbox.com/mapbox.js/v2.1.5/mapbox.js"></script>
  <script src="{{ static('js/jquery.formset.js') }}"></script>
  <script src="{{ static('js/location.js') }}"></script>
  <script src="{{ static('js/fxosprice_new.js') }}"></script>
{% endblock %}

marketpulse/main/templates/home.html
{% extends "base.html" %}

{% block content %}
  <div class="row">
    <div class="col-md-12">

      <div class="text-center">
        <img class="main-image" src="{{ static('img/firefox_os_team.jpg') }}" alt="">
      </div>

      <div class="jumbotron">
        <p>
          Marketpulse is a joint initiative by Mozilla's Participation team and the Fx
          OS Research Team to help Mozillians easily gather local market data and update
          a central dashboard used by the Fx OS team to effectively monitor the reality
          on the ground and gain in-depth market knowledge. For more info, check
          <a href="http://education.mozilla-community.org/modules/marketpulse/participation_ladder/"
             target="_blank">this guide</a>.
        </p>
        <p class="text-center" id="login">
          {{ browserid_login(text='Login with Persona', color='dark') }}
        </p>
      </div>

    </div>
  </div>
{% endblock %}

marketpulse/main/templates/main.html
{% extends "base.html" %}

{% block content %}
  <hgroup id="main-feature" class="huge center">
  </hgroup>

  <div class="row">
  </div>
{% endblock %}